### ISSUE TITLE
"Next Page" Broken

### ISSUE THREAD

**Issue by floatingyuzu** [plexinc-plugins/GiantBomb.bundle#18]
It looks like there is a bug in the __init__.py between line 168 and 176.  In it's current state it's creating the `NewPageObject` but offset is getting messed up. Essentially it should be giving us the next 100 videos each page but right now each page jumps ahead too far. Exactly 100 videos too far. For example in "Latest" the last video of the first page is something from around February 2016, but if you advance to the next page you'll see it jumps to November 2015 during Exra Life.

```
listedSoFar = result['offset'] + result['number_of_page_results']
		if listedSoFar < result['number_of_total_results']:
			newOffset = listedSoFar + result['limit']
			oc.add(
				NextPageObject(
					key=Callback(Videos, cat_id=cat_id, query=query, offset=newOffset),
					title="Next Page"
				)
			)
```
It looks like the logic for creating the `newOffset` is the culprit. On line 173 I tried changing `offset=newOffset` to `offset='100'` as a test, and that did the trick.  This, of course, only worked to display the correct items on page 2 but hopefully it will give someone an idea of how best to make the fix.  Thanks for everyone's work on this project!

**Comment by sander1** [comment]
Thanks for the report! This has been fixed in https://github.com/plexinc-plugins/GiantBomb.bundle/commit/aec468a712952f9709f3909861a952774ede961a, update just pushed out to the Channel Directory.
